apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpl-browser-deployment
  namespace: hpl
  labels:
    app: browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      containers:
      - name: hpl-browser
        image: hpl-browser:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
      volumes:
        - name: config-volume
          configMap:
            name: vue-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vue-config
  namespace: hpl
data:
  config.js: |
    const config = (() => {
      return {
        "SERVICE_MANAGER_ADDRESS": "http://localhost:32354",
      };
    })();

---
apiVersion: v1
kind: Service
metadata:
  name: hpl-browser-service
  namespace: hpl
spec:
  selector:
    app: browser
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
